services:
  - type: web
    name: wortex-osint
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
    plan: free