services:
  - type: web
    name: osint-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TOKEN
        value: 8983546242:AAHVHOfgflOeR4uZoZlbsmdVvjUIF-oiWbQ
      - key: DATABASE_URL
        fromDatabase:
          name: osint-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: osint-redis
          type: redis
          property: connectionString
    plan: free
    autoDeploy: true

databases:
  - name: osint-db
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15

redis:
  - name: osint-redis
    plan: free
    ipAllowList: []